# Generated by Django 5.1.3 on 2024-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('vulnerabilities_found', models.BooleanField(default=False)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
